POST http://localhost:3000/api/v1/cats
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

New cat title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user_id"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="image.jpg"
Content-Type: image/jpeg

< ./image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### get all cats
GET http://localhost:3000/api/v1/cats

###
POST http://localhost:3000/api/v1/cats
Content-Type: application/json

###
POST http://localhost:3000/api/v1/cats

{
  "cat_name": "Whiskers",
  "weight": 5,
  "owner": 3609,
  "filename":"jokufile.jpg",
  "birthdate": "2022-05-15"
}

### update a cat
PUT http://localhost:3000/api/v1/cats/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MCwibmFtZSI6InRlc3R1c2VyIiwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImVtYWlsIjoiYSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQzOTY4MTc5LCJleHAiOjE3NDQwNTQ1Nzl9.lD0CSn-UYpFle2w7MNyxXoR60KSk_YBrXqMgq8YM9ng

{
  "cat_name": "Whiskers",
  "updated_cat_name": "Updated Whiskers",
  "weight": 6,
  "birthdate": "2022-06-01"
}

### include user_id for ownership verification
Authorization: Bearer <eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MCwibmFtZSI6InRlc3R1c2VyIiwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImVtYWlsIjoiYSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQzOTYzNDU1LCJleHAiOjE3NDQwNDk4NTV9.0GC0eCP1vs8SR2YuVrHZfWSeZR9cEJn4hR_Vw7N1YH8>


### delete a cat
DELETE http://localhost:3000/api/v1/cats/41
